projectcalico/typha

cmd/calico-typha/typha.go
Calls EnsureInitialized to make sure the datastore is ain a good state before we start out watches.
=> Ensure datastore is initialized.

cmd/calico-typha/typha.go, pkg/config/config_params.go, pkg/k8s/k8s_suite_test.go, pkg/k8s/lookup.go, pkg/k8s/rebalance.go, pkg/k8s/rebalance_test.go, pkg/syncserver/sync_server.go
Monitor the k8s API to find the number of nodes and number of Typha instances.  Drop connections to rebalance if the load gets too skewed.
=> Add connection count governing.

pkg/syncserver/sync_server.go
Fixes that, if a Typha is unreachable, then the other Typhas aggressively reject connections rather than sharing the load.
=> Back out rejection of incoming connections.

glide.lock, glide.yaml
Rev libcalico/go to pick up https://github.com/projectcalico/libcalico-go/issues/450
=> Rev libcalico-go to 1.4.3 to pick up fixes.

Makefile
The release target talks about pushing the latest tag but it didn't actually generate it.
=> Add quay.io/calico/typha:latest tag to release target.

cmd/typha-client/typha-client.go, fv-tests/doc.go, fv-tests/fv_tests_suite_test.go, fv-tests/server_test.go, pkg/calc/async_decoupler.go, pkg/calc/validation_filter.go, pkg/snapcache/cache.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go, pkg/syncserver/syncserver_suite_test.go, pkg/syncserver/syncserver_test.go, utils/run-coverage
Add FV tests for Typha.  These start the bulk of a Typha server and run those components together.  Allows for testing the server layer, which is tricky to test by mocking.
=> Add FV tests for Typha

Makefile, fv-tests/server_test.go, pkg/config/config_params.go, pkg/config/config_params_test.go, pkg/config/doc.go, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/logutils/logutils.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go
Add the errcheck linter to those that we run.  `errcheck` checks that all error return values are handled.  Fix the bugs that it turned up.
=> Add errcheck linter and fix up the problems it found

glide.lock, glide.yaml
Fix that Felix instances that connected to Typha after some KV churn could be sent a snapshot with missing KVs.
Fixes #28.
The Ctrie datastructure we use had a bug:
If you created two keys, and they ended up in the same “internal node”, *and* it wasn’t the root internal node, *and* there were exactly two items in that node, *and* you deleted one, _then_ the internal node got converted to an optimised “entombed node” and entombed nodes were being skipped when iterating (but not when doing a lookup)
This PR pulls in the fix.
=> Pin go-datastructures library to one with Ctrie traverse fix.

glide.lock, glide.yaml
Rev libcalico-go to a version with the multiple-CIDRs-in-a-rule changes.  This is needed to allow Typha to support Felix instances with that feature.
```release-note
None required
```
=> Rev libcalico-go to pick up multi-net changes.

glide.lock, glide.yaml
Typha part of https://github.com/projectcalico/calico/issues/823 - see there for more details.
=> Advance libcalico-go pin to pick up pre-DNAT policy support

check-licenses/check_licenses.go, cmd/typha-client/typha-client.go, fv-tests/server_test.go, glide.lock, glide.yaml, pkg/calc/async_decoupler.go, pkg/calc/validation_filter.go, pkg/config/config_params.go, pkg/config/env_var_loader.go, pkg/config/file_loader.go, pkg/config/param_types.go, pkg/daemon/daemon.go, pkg/jitter/jittered_ticker.go, pkg/jitter/jittered_ticker_test.go, pkg/k8s/lookup.go, pkg/k8s/rebalance.go, pkg/logutils/logutils.go, pkg/logutils/logutils_test.go, pkg/snapcache/cache.go, pkg/snapcache/cache_test.go, pkg/syncclient/sync_client.go, pkg/syncproto/sync_proto.go, pkg/syncserver/sync_server.go
Updating the logrus import to use the new updated user name (which is lowercased). This will prevent import errors with vendoring going forward.
Requires projectcalico/libcalico-go#484
```release-note
None required
```
=> Update the import for logrus to use the updated username

glide.lock, glide.yaml
We made a fix to go-datastructures to address a Ctrie bug.  That fix was upstreamed so this PR revs to the release with that fix.
```release-note
None required
```
=> Rev go-datastructures to v1.0.39 to pick up fixes.

cmd/typha-client/typha-client.go, fv-tests/server_test.go, pkg/daemon/daemon_test.go, pkg/syncclient/sync_client.go
Fixes #38 by adding a configurable timeout to the Typha client.
```release-note
None required
```
=> Implement read/write timeouts in the Typha client.

glide.lock, glide.yaml
Rev libcalico-go to pick up https://github.com/projectcalico/libcalico-go/pull/524
```release-note
None required
```
=> Rev libcalico-go to pick up permissive ingress/egress validation change.

glide.lock, glide.yaml
bump libcalico-go to v1.7.1. all tests pass
```release-note
None required
```
=> bump libcalico-go to v1.7.1

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
The spec for Typha liveness and readiness reporting is that Typha should report itself as:
- live, so long as its Felix-serving loop has not died or hung
- ready, so long as it is connected to its datastore, and is not doing a resync (either the initial resync, or a subsequent one).
However, if the datastore is unavailable (for some reason) when Typha is started, Typha does not report itself as live because it gets stuck trying to ensure that the datastore is initialized.  This PR fixes that problem.
There is already an FV test for this at https://github.com/projectcalico/felix/blob/master/fv/health_test.go#L419, currently disabled because of the problem that this PR fixes.  Once this PR is merged, that FV test can be enabled again.
=> Don't let datastore connectivity block liveness reporting

pkg/k8s/rebalance_test.go
Seen on this build: https://semaphoreci.com/calico/typha/branches/master/builds/81
Although the channel kicks the background thread before we set `numNodes = 200`, the write may still occur before the background thread reads it.  This results in the updates getting squashed.  Wait for the 31 to be emitted before doing the write.
```release-note
None required
```
=> Fix race in rebalancing test.

glide.lock, glide.yaml, pkg/snapcache/cache.go, pkg/snapcache/cache_test.go
- Force snapshot updates to have updateType=new, this makes sense because they are new to Felix even if they're the result of updates for Typha.  Add machinery to the FVs to check.
- The new machinery found a flake, which I tracked down to https://github.com/Workiva/go-datastructures/issues/180 pin go-datastructures to pick up the fix: https://github.com/Workiva/go-datastructures/pull/182.
Fixes #68 
Fixes #69
```release-note
Fix that Typha could send incorrect updateTypes to Felix during a snapshot leading some Felix statistics being incorrect.
```
=> Fix two issues that resulted in incorrect updateTypes

glide.lock, glide.yaml, pkg/snapcache/cache.go, pkg/snapcache/cache_test.go
Backport #70  to v0.5.x-series.
- Force snapshot updates to have updateType=new, this makes sense
because they are new to Felix even if they're the result of updates
for Typha.  Add machinery to the FVs to check.
- The new machinery found a flake, which I tracked down to
https://github.com/Workiva/go-datastructures/issues/180
pin go-datastructures to pick up the fix:
https://github.com/Workiva/go-datastructures/pull/182.
```release-note
Fix that Typha could send duplicate updates to Felix under certain circumstances.
```
=> v0.5.x: Fix two issues that resulted in incorrect updateTypes

glide.lock, glide.yaml
=> Automated update of libcalico-go to 83fc14937b8584e65bd6c959c0a85256a 2d31e28

glide.lock, glide.yaml
Update libcalico-go to get fix for kdd veth name
```release-note
None required
```
=> Automated update of libcalico-go to 250cb94738bf94032f2af491e362543f346cfac9

Makefile, docker-image/Dockerfile-ppc64le
Signed-off-by: David Wilder <wilder@us.ibm.com>
Adding support for ppc64le build.
The build architecture is select by setting the ARCH environment variable.
For example: When building on ppc64le you could use ARCH=ppc64le make <....>.
When ARCH is undefined builds defaults to amd64.
Note:  
calico-typha and typha-client are now crated as calico-typha-$(ARCH) and typha-client-$(ARCH).   When the docker images is created typha-client is linked to calico-typha-$(ARCH) in the container.  This prevents accidental picking up a stale binary when doing multi arch builds.  Thanks to Casey for this idea.
However,  I could not find a user of typha-client so it is left as typha-client-$(ARCH) in the build directory.
=> Adding support for ppc64le builds.

glide.lock, glide.yaml
Rev libcalico-go to pick up fix to ignore non-global BGP peers
```release-note
None required
```
=> rev libcalico-go to pick up fix to ignore non-global BGP peers

cmd/calico-typha/typha.go, glide.lock, glide.yaml, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
For Kubernetes API datastore clusters, Invoke migration from Typha.
Continuation of #93 by @robbrockbank.  I took his work and reworked it a bit to share the V3 client between the main Typha code and the migrator.  I think that closes some corner cases and avoids leaking a client, which we have no method to fully close.
To do that, I had to make the test shims a bit less nice (the datastore shim now exposes the full client API so that it can be passed into the migrator).
```release-note
None required
```
=> Typha migration

glide.lock, glide.yaml, pkg/daemon/daemon_test.go
Update libcalico-go pin to 5f90a75a16b8c4b94fd045afbfbb545194b451ac
```release-note
None required
```
=> Update libcalico-go pin to 5f90a75a16b8c4b94fd045afbfbb545194b451ac

Makefile
I need go >=1.10 in order to pick up URI SAN handling in crypto/x509 (https://github.com/golang/go/commit/9e76ce70701ceef8fbccfb953b33a2ae7fe0367c)
=> Use go-build 0.14. specifically to get go >=1.10

pkg/config/config_params.go, pkg/config/config_params_test.go, pkg/daemon/daemon.go
Instead of forcing to listen on all interfaces we should give the possibility for the user to make the health server listen on a specific host/ip.
Unit tests are added. Not sure what I can about the integration tests and release notes. Let me know how I can further help.
```release-note
Typha now supports configuring both port and host to bind too for health checks.  The default is now localhost.
```
=> Health server support custom host

fv-tests/server_test.go, pkg/config/config_params.go, pkg/config/config_params_test.go, pkg/daemon/daemon.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go, pkg/tlsutils/tlsutils.go, pkg/tlsutils/tlsutils_suite_test.go, pkg/tlsutils/tlsutils_test.go
Using TLS to encrypt and authenticate the connections between Felix and Typha.
=> Apply TLS to Felix-Typha connections

glide.lock, glide.yaml
Up the pin for `libcalico-go` for Typha. I believe this has to be done from the `projectcalico/typha` branch `automated-libcalico-update` so that we get the right pin of typha on Felix.
=> Update libcalico-go to 5646fa11213b9b5314cca7f5b3aa28ea9811c908

Makefile
Hi, I'm verifying native build on arm64 platform and find this minor issue:
The calico/go-build:v0.14-arm64 does not exist in the public
calico repository which causes build failure on arm64 platform.
```release-note
None required
```
=> Use go-build 0.15, to fix build on non-amd64 platforms.

Makefile
You cannot do this:
```Makefile
@$(MAKE) k8sfv-test
k8sfv-tests: image
cd .. && git clone https://github.com/projectcalico/felix.git && cd felix; \
[ ! -e ../typha/semaphore-felix-branch ] || git checkout $(cat ../typha/semaphore-felix-branch); \
JUST_A_MINUTE=true USE_TYPHA=true FV_TYPHAIMAGE=calico/typha:latest TYPHA_VERSION=latest $(MAKE) k8sfv-test
```
```release-note
None required
```
cc @fasaxc
=> Fix silly typo in Makefile target

pkg/tlsutils/tlsutils.go
Fixes Typha FVs so the CA cert contains the key usage for both server and client. Go 1.10.3 checks that the requested key usage appears in all chained certs when verifying.
```release-note
None required
```
=> Fix FV CA certs re: EKU

Makefile, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le, docker-image/Dockerfile.s390x
**note:** matches the [PR recently merged in for felix](https://github.com/projectcalico/felix/pull/1852)
Before this PR, `ci` and `cd` targets build the binary and the image and push to registry _only_ for `amd64` unless explicitly choosing to add, e.g `make cd ARCH=arm64`. 
This PR makes `ci` and `cd` call the `*-all` targets, thus building binaries and images and pushing to registries for _all_ known arches.
For example:
* `make cd` - push all known arches
* `make cd EXCLUDEARCH=arm64` - push all known arches except `arm64`
* `make cd EXCLUDEARCH="arm64 s390x"` - push all known arches except `arm64` and `s390x`
Same for `make ci`
We have had the `qemu` binaries in `calico/go-build` since v0.15. Why redownload them? Just install them using multistage
Install only the relevant qemu …
=> ci and cd push all arches; ability to exclude specific

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
The change in #140 caused the health endpoint to only listen on localhost.  However, the kubelet checks the health explicitly using the pod IP (which is actually the host IP since typha is host networked) resulting in connection refused.
This change adds a subcommand to the typha executable that checks the health endpoint at `http://127.0.0.1:<port>` so that we can use a [liveness/readiness command](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command) instead of a HTTP check. I.e.
```
livenessProbe:
exec:
command:
- calico-typha
- check
- liveness
periodSeconds: 30
initialDelaySeconds: 30
readinessProbe:
exec:
command:
- calico-typha
- check
- readiness
periodSeconds: 10
```
```release-note
Since Typha no longer exposes …
```
=> Add a health check subcommand.

cmd/typha-client/typha-client.go, fv-tests/server_test.go, glide.lock, glide.yaml, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/syncclient/sync_client.go, pkg/syncproto/sync_proto.go, pkg/syncserver/sync_server.go, utils/run-coverage
Add support for multiple syncer types in Typha and add the BGP syncer.  The client can now request a particular syncer type in its ClientHello message and Typha will respond with the syncer type in its hello message so that the client can verify server support.  (This approach avoids needing to make a breaking change to the protocol since gob ignores unknown fields and we default the the felix syncer if the field is not present.)
Implementation:
- Each syncer gets a separate cache pipeline and separate "breadcrumb" cache.
- The connection handling component passes a map of caches to the individual connection so it can select the right one based on the handshake.
```release-note
None required
```
=> Add multi-syncer support and BGP syncer

glide.lock, glide.yaml
Manual bump needed as automated bump has errors that are actually benign.
=> make update-libcalico

glide.lock
Rev libcalico-go. Had to do this manually of glide running into some issues pulling conflicting deps. Looks like there is precedent to this in prior commits as well.
=> Rev libcalico-go to 3655574dc6162df9974bbdebab072b5ee104b554

docker-image/Dockerfile.amd64
- addresses the issue raised by https://github.com/projectcalico/typha/issues/196
- was able to verify that this change prevents typha from crashing when apiserver goes down.
```release-note
- fixes a bug where typha would crash when kube-apiserver goes down
```
=> create tmp dir to prevent crash from glog 

docker-image/Dockerfile.amd64, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le, docker-image/Dockerfile.s390x, pkg/logutils/logutils.go
Tidy up the solution to #196 . Let me know if this isn't the best place in the codebase for this.
Removes the /tmp dir copy from the base image which is only done to handle glog writing logs to disk.
Instead adds disabling of glog's write to disk behaviour to `ConfigureEarlyLogging` to disable the behaviour as fast as possible. Same behaviour as now used by [kube-controllers](https://github.com/projectcalico/kube-controllers) after https://github.com/projectcalico/kube-controllers/pull/361
This repo isn't yet using a new enough version of client-go to need the klog behaviour disabling but have left a comment in the glog disabling.
Tested successfully in our cluster both with just removing the tmp dir and causing the expected crash of the pod and with the new code.
<details> …
=> Disable Glog logging to disk

glide.lock, glide.yaml
Do not merge until https://github.com/projectcalico/libcalico-go/pull/1068 is merged and vendoring is updated.
```release-note
None required
```
=> glide: update libcalico-go to have new Felix config params

glide.lock, glide.yaml
This is to fix issues with missing file and line number information
after bumping the version to 1.0.6.
See https://github.com/projectcalico/libcalico-go/pull/1074
=> Use calico fork of logrus

glide.lock, glide.yaml
Which adds new sockmap fields.
~Blocked on https://github.com/projectcalico/libcalico-go/pull/1093.~
```release-note
None required
```
=> glide: update libcalico-go to have new Felix config

pkg/config/config_params.go
Using joinHostPort allows us to reuse input validation on HealthHost as well.
=> Make prometheus host input validation generic and apply it to HealthHost

fv-tests/server_test.go, pkg/syncclient/sync_client.go, pkg/syncproto/sync_proto.go, pkg/syncserver/sync_server.go
This is a follow-on PR to recent work to add VXLAN cross-subnet support. One of those PRs added a full node object to the Felix update processor: https://github.com/projectcalico/libcalico-go/pull/1115 
This PR allows Typha clients to know whether the Typha server supports node resource updates (by being compiled with a libcalico-go that includes it). If the Typha server does not support node resource updates and VXLAN cross-subnet is configured, then Felix will proceed as if VXLAN "always" was configured.
Once this is merged, a corresponding change to Felix is required in the case where Typha is enabled:
- After the Typha connection is created, call `typhaConnection.SupportsNodeResourceUpdates`
- Use the response to update config params that are eventually used to …
=> Support node resource update handling in handshake

Makefile
Without this, we miss extra args in the local build, which causes go module replacement of the ../lib-calico/ library for the builder to fail.  Huge thanks to @rafaelvanoni  for helping me find this !!!
```release-note
fix 3.10 build stanza for LOCAL_BUILD to read docker extra args after they are set .
```
=> Move EXTRA_ARGS "up in the world"

Makefile
The invocation make tag-images-all RELEASE=true IMAGETAG=<tag> was not tagging and pushing the image to gcr.io registries.
This PR addresses part of that: the PUSH_IMAGES variable needs to be defined before Makefile.common is included, otherwise PUSH_IMAGES will lose its initial default values. The second part is fixed in the common Makefile in projectcalico/go-build#95
```release-note
None required
```
=> Ensure appending to PUSH_IMAGES is not part of a recipe

.dockerignore, Makefile, docker-image/Dockerfile.amd64, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le, docker-image/Dockerfile.s390x
Pick of https://github.com/projectcalico/typha/pull/328
```release-note
Update typha image to meet openshift certification requirements. 
```
=> release-v3.12 - Cherry-pick Update amd64 image to meet certification requirements (#328)

.dockerignore, Makefile, docker-image/Dockerfile.amd64, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le, docker-image/Dockerfile.s390x
Pick of https://github.com/projectcalico/typha/pull/328
```release-note
Update typha image to meet openshift certification requirements. 
```
=> release-v3.11 - Cherry-pick Update amd64 image to meet certification requirements (#328)

README.md
This fixes the guide link + removes the node-count recommendation based on the current [Operator](https://github.com/tigera/operator) deployment.
=> README: link fix + node-count recommendation

go.mod, pkg/calc/node_counter.go, pkg/daemon/daemon.go, pkg/k8s/lookup.go
Typha is already watching Node objects through the Syncer so drive it off that!
I also haven't optimized the Get() for the Endpoints object used to determine the number of Typhas - maybe we should, but it should be a really low-traffic call and I wouldn't expect it to have performance impact. 
```release-note
Typha no longer uses Get requests to determine the number of nodes in the cluster, using watches instead. 
```
=> Don't List nodes, watch them!

pkg/config/config_params.go
It now returns "" instead of "etcdv3" if it doesn't find its expected environment variable.
This quick fix should restore the old behaviour but we may want to clean this up further.  Shouldn't libcalico-go set the default?
```release-note
None required
```
=> Respect new libcalico-go datastore type defaulting behaviour.

go.mod, go.sum, pkg/config/config_params.go
libcalico-go now defaults to kubernetes mode so, either we handle the datastore in the `config.DatastoreType == etcdv3` branch or LoadClientConfigFromEnvironment will do the right thing.
```release-note
None required
```
=> Rev libcalico-go and remove datastore defaulting.

fv-tests/server_test.go, pkg/snapcache/cache_test.go, pkg/syncproto/sync_proto.go
Since the v3 resources have an embedded resource version, dedupe was always
failing.
May fix https://github.com/projectcalico/calico/issues/4129
```release-note
None required
```
=> Fix v3 resource deduplication.

fv-tests/server_test.go, pkg/snapcache/cache_test.go, pkg/syncproto/sync_proto.go
Backport #449 
Fix v3 resource deduplication.
```release-note
Fix that Typha was unable to deduplicate Calico v3 Node resources.  This caused excessive CPU usage in Felix.
```
=> [v3.17] Backport v3 resource deduplication fix

fv-tests/server_test.go, pkg/snapcache/cache_test.go, pkg/syncproto/sync_proto.go
Backport #449 
Fix v3 resource deduplication.
(cherry picked from commit 2ecea02454e8f22b8844d1b3b50e30001b4b451d)
```release-note
Fix that Typha was unable to deduplicate Calico v3 Node resources.  This caused excessive CPU usage in Felix.
```
=> [v3.16] Backport v3 resource deduplication fix

fv-tests/server_test.go, pkg/config/file_loader_test.go, pkg/snapcache/cache_test.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go
* Remove maximum TLS version.  Should no longer be needed.
* Remove unneeded TLS config to set the RNG; the tls implementation
already uses the secure RNG by default.
```release-note
For improved security, the Typha/Felix API now requires TLS v1.2+.
```
=> Increase minimum TLS version to v1.2 for improved security.

.gitignore, go.mod, pkg/discovery/discovery.go, pkg/discovery/discovery_suite_test.go, pkg/discovery/discovery_test.go, pkg/syncclientutils/startsyncerclient.go
Backport of #462  #463  #464 
(cherry picked from commit 71903c810b3d31cbd47f7a2b9bf7815ac51a453d)
(cherry picked from commit de365c2dc753a6ac8d11176179709708b040fbbf)
(cherry picked from commit ff204c3515d51d3f7572c9cd0e0b5858e9210cd8)
(cherry picked from commit 04f6aec37b10de20d53278c71928c7487c08f0d8)
```release-note
All components that use Typha now use the same logic to discover Typha's address.  They lookup the endpoints of the service directly and connect to one at random.  This avoids a dependency on kube-proxy.
```
=> [v3.17] Backport: Move kubernetes discovery to Typha so it can be shared.

.semaphore/clear_cache.yml, .semaphore/semaphore.yml, .semaphore/update_pins.yml
Semaphore v1 can no longer build Typha due to the docker account requirement.  Backport the Semaphore v2 build.
```release-note
None required
```
=> [v3.16] Backport Semaphore v2 builds

.gitignore, go.mod, pkg/discovery/discovery.go, pkg/discovery/discovery_suite_test.go, pkg/discovery/discovery_test.go, pkg/syncclientutils/startsyncerclient.go
Backport of #462  #463  #464 
(cherry picked from commit 71903c810b3d31cbd47f7a2b9bf7815ac51a453d)
(cherry picked from commit de365c2dc753a6ac8d11176179709708b040fbbf)
(cherry picked from commit ff204c3515d51d3f7572c9cd0e0b5858e9210cd8)
(cherry picked from commit 04f6aec37b10de20d53278c71928c7487c08f0d8)
```release-note
All components that use Typha now use the same logic to discover Typha's address.  They lookup the endpoints of the service directly and connect to one at random.  This avoids a dependency on kube-proxy.
```
=> [v3.16] Backport: Move kubernetes discovery to Typha so it can be shared.

Makefile
Cherry pick of #468 on release-v3.16.
#468: Fix make cd target to use correct tag for docker images
=> Automated cherry pick of #468: Fix make cd target to use correct tag for docker images

Makefile
Cherry pick of #473 on release-v3.17.
#473: Fix make cd target to use correct tag for docker images
=> Automated cherry pick of #473: Fix make cd target to use correct tag for docker images

fv-tests/server_test.go, pkg/snapcache/cache_test.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go
Backport of #457 
Increase minimum TLS version to v1.2 for improved security.
(cherry picked from commit 02cb7ab48db1576d286a5aca343b8e7f0b8e3bdd)
```release-note
For improved security, then using TLS, the Felix-Typha API now requires a minimum TLS version of v1.2.
```
=> [v3.16] Backport setting minimum TLS version to v1.2

fv-tests/server_test.go, pkg/config/file_loader_test.go, pkg/snapcache/cache_test.go, pkg/syncclient/sync_client.go, pkg/syncserver/sync_server.go
Backport of #457 
Increase minimum TLS version to v1.2 for improved security.
(cherry picked from commit 02cb7ab48db1576d286a5aca343b8e7f0b8e3bdd)
```release-note
For improved security, then using TLS, the Felix-Typha API now requires a minimum TLS version of v1.2.
```
=> [v3.17] Backport setting minimum TLS version to v1.2

fv-tests/server_test.go, fv-tests/state_recorder.go, go.sum, pkg/config/config_params.go, pkg/daemon/daemon.go, pkg/syncserver/sync_server.go, pkg/syncserver/syncserver_test.go
We've seen felix get cyclicly booted from the server, presumably
because sending the snapshot took an unexpectedly long time due
to CPU or netowrk contention.
Add an extra grace period for newly-connected clients so that
they get some time to catch up after the snapshot is sent. Hopefully,
that will solve the problem outright but it also has the side effect
of giving the new felix some time to update the dataplane before we
kill the Typha connection.  This ensures that it makes progress
even if it's restarting.
```release-note
Typha now gives newly connected clients an extra grace period to catch up after sending the snapshot.  Should reduce the possibility of cyclic disconnects.
```
=> Add an extra grace period for new connections

Makefile
Cherry pick of #635 on release-v3.20.
#635: Fix release image tagging
=> Automated cherry pick of #635: Fix release image tagging

pkg/syncserver/sync_server.go
Cherry pick of #694 on release-v3.21.
#694: Restrict Typha server to FIPS compliant cipher suites
```release-note
Restrict Typha server to FIPS compliant cipher suites. 
```
=> Automated cherry pick of #694: Restrict Typha server to FIPS compliant cipher suites
