projectcalico/typha

pkg/snapcache/snapshot_cache.go, pkg/syncproto/sync_proto.go
This was broken by addition of revision information to the SerializedUpdate.
I've tested it manually in a small rig.
=> Fix deduplication of unchanged KVs. 

cmd/calico-typha/typha.go
Remove some Felix left-overs:
- Datastore config loading was half-baked because we weren't wathing it for changes.
- Felix's manage shutdown function not needed.
=> Remove datastore config loading and clean up shut down.

pkg/snapcache/cache.go, pkg/snapcache/cache_test.go, pkg/snapcache/snapcache_suite_test.go, pkg/syncserver/sync_server.go
Add UT/FVs for the snapshot cache.
=> Add UTs for the snapshot cache

pkg/jitter/jittered_ticker.go
I need this improved ticker to ensure that the FV tests shut down quickly and cleanly.  Previously, the ticker would stop only when it next ticked.
=> Make jittered ticker stop immediately.

pkg/syncserver/sync_server.go
Adding UTs for this under my UT branch but wanted to make sure the fix was split out.
=> Fix config defaulting copy/paste errors.

fv-tests/server_test.go
=> Add FV test that tests many adds and deletions.

.github/PULL_REQUEST_TEMPLATE.md
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
=> Add release notes to PR template

glide.lock, glide.yaml
Update glide to use libcalico-go ^v1.5.0
```release-note
None required
```
=> Update glide pins

pkg/snapcache/cache.go, pkg/snapcache/cache_test.go
Previously waited for the timer to pop, which could be another 10s.
Fixes #35 
```release-note
None required
```
=> Report readiness eagerly whenever the sync status changes.

glide.lock, glide.yaml
Update to libcalico v1.6.0
```release-note
None required
```
=> Update libcalico to v1.6.0.

glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to pick up KDD syncer fix.

glide.lock, glide.yaml
Rev libcalico-go to pick up v2 datamodel fixes.
```release-note
None required
```
=> Rev libcalico-go to pick up fixes.

glide.lock, glide.yaml
Pick up permissive named ports validation.
```release-note
None required
```
=> Rev libcalico-go

glide.lock, glide.yaml, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
Remove EnsureInitialized call and associated irrelevant UTs
```release-note
None required
```
=> Remove EnsureInitialized call and associated irrelevant UTs

glide.lock, glide.yaml
upgrade libcalico-go
```release-note
None required
```
=> upgrade libcalico-go

glide.lock, glide.yaml
Specifically to get the labels -> labelsToApply change
=> Rev to latest libcalico-go

Makefile, glide.lock, glide.yaml
Also rev the go-build container to pick up CVE fixes.
```release-note
None required
```
=> Rev libcalico-go to version including named port duplicates fix.

Makefile
Update the build container to pick up new version of go and various CVE fixes.
```release-note
Typha is now build with go 1.9.2.
```
=> Rev go-build container to v0.9 to pick up go v1.9.2.

glide.lock, glide.yaml, pkg/config/config_params.go
Also, make etcdv3 the default datastore type.
```release-note
None required
```
=> Update libcalico for namespace selector support

glide.lock, glide.yaml, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
- Revert the backing out of the ready flag/EnsureInit.
- Update to use v2 API.
```release-note
None required
```
=> Reinstate EnsureInitialized calls and use V2 client

glide.lock, glide.yaml
```release-note
None required
```
=> Update of libcalico-go

glide.lock, glide.yaml, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
Rev libcalico-go and update clientv2 and apiv2 references
Part of the updating of v2 -> v3
```release-note
None required
```
=> Rev libcalico-go and update clientv2 and apiv2 references

glide.lock, glide.yaml, pkg/calc/validation_filter.go
update libcalico-go pin
```release-note
None required
```
=> update libcalico-go pin

glide.lock, glide.yaml
Rev libcalico-go to v1.7.3
```release-note
None required
```
=> rev libcalico-go to v1.7.3

glide.lock
Need to integrate with libcalico-go changes with http and service account support.
```release-note
None required
```
=> update of libcalico-go to master

glide.lock, glide.yaml
Bumping libcalico-go to match Felix PR.
```release-note
None required
```
=> Bumping libcalico-go

glide.lock, pkg/daemon/daemon.go
Bumping libcalico-go to pickup new health changes, and updating API changes.
```release-note
None required
```
=> Bumping libcalico and fixing health calls

pkg/daemon/daemon.go
Avoid logging that migration is not required after doing the migration.
```release-note
None required
```
=> Squash spurious migration log.

pkg/logutils/logutils.go
Continuation of #104.
```release-note
Typha now logs to stdout instead of stderr, which prevents fluentd from interpreting all our logs as errors.
```
=> Log to stdout

pkg/logutils/logutils.go
```release-note
None required
```
=> Log to stdout instead of stderr

glide.lock, glide.yaml, pkg/daemon/daemon_test.go
```release-note
None required
```
=> Rev libcalico-go to pick up GlobalNetworkSets.

glide.lock, glide.yaml
Bringing master to a modern libcalico, including KDD HostEndpoints as well.
```release-note
None required
```
=> Update libcalico-go to 8439a792041f7cb676bc339dffccf30e165a9ec3

glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to d2fe70a7fc26fff6b08f2f91214cd129ec12426e.

Makefile, docker-image/Dockerfile-s390x
=> Added support for s390x

glide.lock, glide.yaml
Let's try this again. Update libcalico-go rev https://github.com/projectcalico/libcalico-go/pull/829
=> Update libcalico-go to f94d044d5357e7d8939fec43efc14124408cd2b9

glide.lock
(Manually, because using glide pulled in a lot of unwanted floating deps.)
```release-note
None required
```
=> Rev libcalico-go.

Makefile, docker-image/Dockerfile, docker-image/Dockerfile.amd64, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le, docker-image/Dockerfile.s390x
This PR adds:
* Support for cross-compiling, so you can compile `arm64` while on `amd64`, etc.
* matches the approved and merged design style in [felix cross-compile](http://github.com/projectcalico/felix/pull/1703)
* adds a few additional targets `build` and `image` to match the targeted (bad pun intended) standardization of target names
* adds `arm64` Dockerfile
As discussed with @fasaxc and @caseydavenport 
Support for arm64; support for compiling for all supported platforms from amd64.
```release-note
None required
```
=> Support for cross-compiling

Makefile, docker-image/Dockerfile-s390x
Backport of support for s390x #114
```release-note
Backport s390x build support
```
=> [v3.0] Backport s390x build support

Makefile, docker-image/Dockerfile.arm64, docker-image/Dockerfile.ppc64le
The earlier PR [here](http://github.com/projectcalico/typha/pull/127) missed some key elements for cross-compiling. Thanks to @djlwilder for finding them and alerting me. This one completes the missing elements.
```release-note
Complete cross-compile support.
```
=> Add missing cross-compile elements

docker-image/Dockerfile.amd64
- Add missing PATH.
- Bring into sync with other arches (use scratch)
```release-note
None required
```
=> Fix up AMD64 dockerfile.

check-licenses/check_licenses.go, glide.lock, glide.yaml
See https://github.com/projectcalico/felix/issues/1789
```release-note
None required
```
=> Pin etcd client to commit in our repo with a fix for tight loop.

Makefile
```release-note
None required
```
=> Add GCR image tagging and pushing

glide.lock, glide.yaml
This is in service to https://github.com/projectcalico/felix/pull/1838
=> Bump libcalico-go dependency

Makefile
Add arch to gcr.io tagged images. default "arch-less" for `amd64` already is in place.
```release-note
None required
```
cc @fasaxc
=> Add arch to tagged images for gcr

glide.lock, glide.yaml
```release-note
None required
```
=> Automated libcalico pin update

Makefile
```release-note
None required
```
=> Makefile: Stop uploading to coveralls

Makefile
Cherry pick of https://github.com/projectcalico/typha/pull/194/commits
```release-note
None required
```
=> cherry-pick: Fix release

Makefile
```release-note
None required
```
=> Support building from local code checkouts

docker-image/Dockerfile.amd64
https://github.com/projectcalico/typha/pull/211
=> [release-v3.3] cherry pick: glog fix

docker-image/Dockerfile.amd64
https://github.com/projectcalico/typha/pull/211
=> [release-v3.2] cherry pick: glog fix

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.5

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.4

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.3

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go and felix pin update for release v3.2

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.1

glide.lock, glide.yaml
```release-note
None required
```
=> libcalico-go pin update for release v3.0

Makefile
```release-note
None required
```
=> backport release changes to v3.0

Makefile
```release-note
None required
```
=> Backport release improvements to v3.1

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go
```release-note
None required
```
=> Remove health check command

glide.lock, glide.yaml, pkg/daemon/daemon_test.go
Fixed tests by implementing NetworkSets for mockDatastore
```release-note
None required
```
=> Implement missing NetworkSets for mockDatastore

Makefile, glide.lock, glide.yaml, pkg/daemon/daemon.go
```release-note
None required
```
=> Update of libcalico-go to pull in host-local changes

glide.lock, glide.yaml
```release-note
None required
```
=> Pin libcalico-go to 8f3f0bcb367892403be12b2579377c0afab8094b

glide.lock, glide.yaml
```release-note
None required
```
=> Rev libcalico-go to pick up sidecar acceleration flag name change.

glide.lock, glide.yaml
```release-note
None required
```
=> [v3.8] Rev libcalico-go to pick up iptables-1.8 feature backport.

go.mod, go.sum
```release-note
None required
```
=> Update libcalico to pull in service cluster IP changes

README.md
Fixes a typo in the README.
```release-note
None required
```
=> README: fix subtest title typo

check-licenses/check_licenses.go, glide.lock, glide.yaml, pkg/logutils/logutils.go
For serviceaccount projection support.
```release-note
Update client-go to support BoundServiceAccountTokenVolumes 
```
=> Use client-go v12.0.0

go.mod, go.sum
libcalico-go pin rev to get namespaces networks fix
n/a
n/a
```release-note
None required
```
=> Rev libcalico-go pin

go.mod, go.sum
Signed-off-by: Spike Curtis <spike@tigera.io>
Pin update to include rule metadata
```release-note
None required
```
=> Update libcalico pin for rule metadata

docker-image/Dockerfile.amd64, docker-image/nsswitch.conf
Based off of what we do for calico/node: https://github.com/projectcalico/node/pull/70/files
Fixes https://github.com/projectcalico/typha/issues/311
```release-note
Add nsswitch.conf to Typha for correct resolution of localhost
```
=> Add nsswitch.conf to docker image

Makefile
```release-note
None required
```
=> Cherry-pick Ensure appending to PUSH_IMAGES is not part of a recipe (#346)

pkg/config/config_params.go, pkg/k8s/rebalance.go, pkg/k8s/rebalance_test.go
https://github.com/projectcalico/typha/issues/291
=> Typha connections limit needs to account for confd

go.mod, go.sum, pkg/daemon/daemon_test.go
```release-note
None required
```
=> Update libcalico pin

README.md, docker-image/licenses/Apache-2.0, docker-image/licenses/BSD, docker-image/licenses/ISC, docker-image/licenses/MIT, docker-image/licenses/Mozilla-public
```release-note
None required
```
=> Include more license information

pkg/calc/calc_suite_test.go, pkg/calc/calc_test.go, pkg/calc/validation_filter.go
```release-note
None required
```
=> Use v3 validator for v3 resources

cmd/typha-client/typha-client.go, fv-tests/server_test.go, go.sum
Found this useful when doing some scale testing and prototyping recently.
```release-note
None required
```
=> Add TLS to the dummy typha client.

go.mod, go.sum
```release-note
None required
```
=> Update to latest libcalico-go pin

.gitignore, README.md, docker-image/Dockerfile.amd64, docker-image/licenses/Apache-2.0, docker-image/licenses/BSD, docker-image/licenses/GPLv2, docker-image/licenses/ISC, docker-image/licenses/MIT, docker-image/licenses/Mozilla-public
```release-note
None required
```
=> Add licenses to docker image

.gitignore, README.md, docker-image/Dockerfile.amd64, docker-image/licenses/Apache-2.0, docker-image/licenses/BSD, docker-image/licenses/GPLv2, docker-image/licenses/ISC, docker-image/licenses/MIT, docker-image/licenses/Mozilla-public
Cherry pick of #364 on release-v3.14.
#364: Add licenses to docker image
=> Automated cherry pick of #364: Add licenses to docker image

Makefile
```release-note
None required
```
=> Update go-build version to fix pin-updates

go.mod, go.sum
```release-note
None required
```
=> Update of libcalico-go pin

go.mod, go.sum
```release-note
None required
```
=> update libcalico-go pin for EndpointSlicesEnabled config option

pkg/config/config_params.go, pkg/k8s/rebalance.go, pkg/k8s/rebalance_test.go, pkg/syncclientutils/config.go
- Default the namespace when building config from env vars, if not
explicitly set.
- Update connection rebalancing to account for a third Typha client.
```release-note
None required
```
=> Changes to support an additional typha client (IP allocator)

pkg/config/config_params.go, pkg/k8s/rebalance.go, pkg/k8s/rebalance_test.go, pkg/syncclientutils/config.go
Cherry pick of #378 on release-v3.15.
#378: Changes to support an additional typha client (IP allocator)
=> Automated cherry pick of #378: Changes to support an additional typha client (IP allocator)

go.mod, go.sum
```release-note
None required
```
=> libcalico-go pin updates

Makefile
```release-note
None required
```
=> Update gobuild v0.45

.semaphore/semaphore.yml
```release-note
None required
```
=> Migrate to Semaphore v2

.semaphore/semaphore.yml
```release-note
None required
```
=> Tidy update semaphore v2 build, fix caching issue

.semaphore/clear_cache.yml, .semaphore/semaphore.yml
```release-note
None required
```
=> Use unique cache key and add clear cache promotion

go.mod, go.sum
```release-note
None required
```
=> Rev libcalico-go to pick up BPF fixes.

pkg/daemon/daemon.go
```release-note
None required
```
=> Log out Kubernetes connection parameters for easier debugging.

pkg/daemon/daemon.go
```release-note
None required
```
=> V3.16 log out k8s params

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> Pick up felixconfiguration updates 

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> [release-v3.16] Pick up felixconfiguration updates

go.mod, go.sum
Adds knobs for explicitly allowing encap traffic.
```release-note
None required
```
=> [release-v3.15] Pick up felixconfiguration updates

.semaphore/semaphore.yml, .semaphore/update_pins.yml, Makefile
```release-note
None required
```
=> Add update_pins pipeline to trigger pin updates

Makefile
```release-note
None required
```
=> Delete common makefiles on clean

.semaphore/semaphore.yml, Makefile
```release-note
None required
```
=> Trigger felix pin update on merge to master or release branches

pkg/config/config_params_test.go
```release-note
None required
```
=> gomega.Default conflicts with config.Default

go.mod, go.sum
```release-note
None required
```
=> Update pins (for BGP password support)

pkg/config/config_params_test.go, pkg/config/env_var_loader_test.go, pkg/config/file_loader_test.go, pkg/config/param_types_test.go
```release-note
None required
```
=> Rework so that gomega is always a dot import

Makefile
```release-note
None required
```
=> Trigger confd pin update (instead of libcalico-go)

.gitignore, go.mod, pkg/discovery/discovery.go, pkg/discovery/discovery_suite_test.go, pkg/discovery/discovery_test.go
Previously, Felix, confd and node had their own discovery logic.  This pulls the version from Felix into this repo so it can be reused.
```release-note
Typha now exports a discovery API for other components to use.
```
=> Move typha endpoint discovery to this repo so it can be shared

pkg/discovery/discovery.go, pkg/syncclientutils/startsyncerclient.go
Turns out that there was already a shared copy of the discovery logic from #462  in typha.  Coalesce the two.
```release-note
None required
```
=> Coalesce multiple versions of the discovery logic.

pkg/discovery/discovery.go
```release-note
None required
```
=> Fix name of discovery flag.

pkg/daemon/daemon.go, pkg/snapcache/cache.go, pkg/snapcache/cache_test.go
This PR adds separate health reporters for each syncer pipeline.  The process will not report ready until all pipelines have become in-sync.
```release-note
None required
```
=> Readiness depends on all syncers

Makefile
```release-note
None required
```
=> Fix release image tagging

Makefile
Cherry pick of #641 on release-v3.20.
#641: Change release repo to docker.io, add RELEASE and CONFIRM env
=> Automated cherry pick of #641: Change release repo to docker.io, add RELEASE and CONFIRM env

.semaphore/semaphore.yml
Fix semaphore runs that were running out of space.
```release-note
None required
```
=> Clear up space for semaphore builds

.semaphore/semaphore.yml
```release-note
None required
```
=> Unmount the pre-loaded image cache for semaphore

.semaphore/semaphore.yml
Seeing a smattering of no spec left on device errors on the builds - not so much in master but in other releases.  Guessing it makes sense to address in master though.
```release-note
None required
```
=> Increase VM size for build

.semaphore/semaphore.yml
```release-note
None required
```
=> Add missing unshallow to semaphore.yml.

pkg/syncserver/sync_server.go
```release-note
Restrict Typha server to FIPS compliant cipher suites. 
```
=> Restrict Typha server to FIPS compliant cipher suites
